travis:
  secure:
    BINSTAR_TOKEN: C7OuK65BFtcGLz8Cz4pYyupfmiK+hmBqhFqL6+hSUZPEom5gofpcs546qEwvuM03IPRxjt4tfV3D3LL3+ZkpTjCIRpehZtUVprzB46J1rS9LtgUZ248cL5pmyw4TtqF8gi3xP9uTM/VGz0Q+r3g14My4hWSz8ZBelLsCrNz2aMedOK35k6AF0AqsYNMlIy1ORcREz3x1yseP1TDeJlbAbskNo4W47357zRPrIB9P24RpXHTSt5lpGUorLykPXMUZEfgLvX4bd/zBDi3n8CiyH8XbjD65rDSwGYsxx3IQ857z0rW43qtXwy0JI+kvnXJiPpylmb6yHwtYlMR0ox3SX0e+ug1yTdcprX4iZaR+B4VoG4TEtXHC7cYozcmP7K6aDT9iM+cD5FTdwPnWozR+8q4+ob2esla5pQ+H2srYW6c2sx1/50xGGmMeeHTyQfEe/0+dNtCST9UixkapE6pJhqYICja1dErF4vBnKmGXWACkHnR7lplwUr2GnamowH4P7YzjzuOd2hEcLxpCS+4BjUSp1M7vkYbOcXIAxL2W6kqE2smS7BdAxH3/50PMDmDbbaViD4MDnmZ2Flv1Z0YozWPw1iEABo6QU/O9xX2UGvobgfdHOG/xlAqwcCZRqh0GotnE6sSaTh0xRBfQsLuVGdZZ1cng+cfn+4DA/RtIWww=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
